name: release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: version
        run: echo "::set-output name=version::$(grep '"version":' manifest.json | tr --delete '" ,' | sed 's/version://')"
        id: version
      - name: changelog
        run: "::set-output name=changelog::$(git log --oneline $(git describe --tags --abbrev=0 @^)..@)"
        id: changelog
      - name: build artifacts
        run:  make xpi
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ReplyWithHeaderMozilla-${{ steps.version.outputs.version }}.xpi
          asset_name: ReplyWithHeaderMozilla-${{ steps.version.outputs.version }}.xpi
          tag: ${{ github.ref }}
          overwrite: true
          body: ${{ steps.changelog.outputs.changelog }}
